### ISSUE TITLE
strong rolloff before 19000 HZ

### ISSUE THREAD

**Issue by capoei** [molke-productions/qloud#15]
when I conect output to input and meassure (to 20000HZ) there is a strong rolloff before 19000 HZ.
also when I import the resulting meassurement into REW there is up to half a dB of riple below 100Hz

**Comment by molke-productions** [comment]
If I remember correctly, some kind of roll-off is to be expected with an FFT-based analysis. You would have to increase the maximum frequency well above 20 kHz (limited to half the sampling rate—just using 22050 Hz results in an almost flat curve for me) if you really want to measure up to 20 kHz. Frequency resolution is also related to window size.

**Comment by capoei** [comment]
ok, Qloud creates two files (x)ir.wav after the meassurement, and (x)irTrimmed.wav after ploting a graph.
I expected (x)ir.wav to be a pure IR without windowing. So this is not the case?
btw: confirmation that 22050 almost gives flat response to 20kHz

**Comment by molke-productions** [comment]
Sorry for the delay. All of the WAV files are somehow processed due to the method used here (see the AES preprint by Angelo Farina linked in the Readme). I don’t know if this is involves windowing for the untrimmed files. I would rather see those as an internal representation.
