### ISSUE TITLE
Picker and moving would be handy

### ISSUE THREAD

**Issue by gaydenko** [molke-productions/qloud#16]
Hi!

I very appreciate the project maintaining and idiomatic modifications towards new dep libs!

Today suddenly (really, few years were without) I have decided to measure something. On browsing result I have found it would be handy to restore values-on-cursor picker (say, Hz and Db for SPL) as well as canvas moving.

Just small RFE :)

**Comment by be1** [comment]
@gaydenko Sorry for my bad english, but can you emphasise values-on-cursor word ? Do you mean, Hz/dB should be displayed on the cursor when hovering or left-clicking the plot, or something like that ?

**Comment by gaydenko** [comment]
@be1 Exactly! In my initial implementation a label was attached to cursor to show current axes values. It is really very, very handy. I would say, at my case it is 40% of overall sense of the app :)

**Comment by be1** [comment]
> @be1 Exactly! In my initial implementation a label was attached to cursor to show current axes values. It is really very, very handy. I would say, at my case it is 40% of overall sense of the app :)

Okay, I am going to implement this (back).

**Comment by gaydenko** [comment]
> Okay, I am going to implement this (back).
It's really great, thanks!

**Comment by gaydenko** [comment]
> Please tell me if you are satisfied with this Fix. Or If I should display, for example, a dashed vertical line on cursor position, or something else, for your needs

You are very fast :)

I would:

- place the label below cursor on the right hand
- render each number on own row (that is two row)
- use units (Hz, dB, ms)
- use integer number for Hz and ms
- use two fractional digit for dB
- reduce font contrast a bit

For me Y value is not in par with cursor at the moment - I see something strange :)

**Comment by be1** [comment]
Thanks for your suggestions. I will try to implement them.

**Comment by be1** [comment]
I got almost all of it pushed. But I would like to display phase degrees (in the tooltip) in addition to SPL. Sadly I cannot find an elegant way to get the degree unit string "°" for that plot (phase) which is an exception.

**Comment by gaydenko** [comment]
> I got almost all of it pushed. But I would like to display phase degrees (in the tooltip) in addition to SPL. Sadly I cannot find an elegant way to get the degree unit string "°" for that plot (phase) which is an exception.

Don't know about others, but I don't use phase :)
Yes, this decoration is more readable (for my eyes at least).

I still get strange Y values - http://gaydenko.com/tmp/qloud-tooltip01.png Probably it can be related the fact I use 4K monitor with 2x scaling.
Also, is there an opportunity to distant a tooltip from cursor a bit? To my taste it is very close to cursor at the moment.

**Comment by be1** [comment]
> I still get strange Y values - http://gaydenko.com/tmp/qloud-tooltip01.png Probably it can be related the fact I use 4K monitor with 2x scaling.

The displayed value is the dB (of the curve!) at x position of the cursor. the y position of the cursor is useless. In your screenshot, it seems -9.35 dB is the correct value if you have a 2dB per line scale, wherever the y position of the cursor is.

**Comment by gaydenko** [comment]
> The displayed value is the dB (of the curve!) at x position of the cursor. the y position of the cursor is useless. In your screenshot, it seems -9.35 dB is the correct value if you have a 2dB per line scale, wherever the y position of the cursor is.

Aha, I see - I was under pressure of all habits when Y was connected to cursor rather than to graph. Yes, this new way is better, thanks!

**Comment by be1** [comment]
> Aha, I see - I was under pressure of old habits when Y was connected to cursor rather than to graph. Yes, this new way is better, thanks!

I admit this can be confusing... sorry. Maybe I should draw a whole vertical line following the cursor ? This would cross the curve and graphically confirm the value of the tooltip... Do you think would be a good idea ? Or do you think it's really better displaying the cursor's y instead of the curve's y ?

**Comment by gaydenko** [comment]
> I admit this can be confusing... sorry.

No-no, it was just my case because of old habits. The new way is better! 

And I'm not sure vertical line will be useful. To my taste current variant is very acceptable (except for tooltip is too close to cursor).

**Comment by be1** [comment]
> To my taste current variant is very acceptable (except for tooltip is too close to cursor).

Thanks. Now is the tooltip still to close when the cursor is a _cross_, as in the newest commit ? On my display (1600x900) this is rather not close. But I'm not shure it works the same on any display... Not sure I an fix that.

**Comment by gaydenko** [comment]
> Now is the tooltip still too close when the cursor is a _cross_, as in the newest commit ? On my display (1600x900) this is rather not close. But I'm not shure it works the same on any display... Not sure I can fix that.

For me the cross looks better.

And, well, don't take my opinion seriously - it's just one of infinite ones :) As far as you are implementing the feature, I guess, it is expected you will get satisfaction of the finite result in your own. Say, if you find vertical line works/looks better, use it! At any case some short users' adaptation to any details is not an issue as far as functionality is on the place.

And, of course, somebody's else opinions would be valuable.

**Comment by be1** [comment]
Thank you :)
I added a dashed vertical line crossing the curve. I find it more natural.

**Comment by be1** [comment]
@molke-productions would you be okay if I tag qloud as 1.4.2 after this feature ?

**Comment by molke-productions** [comment]
Sure, and thank you for (re)implementing.

After finally getting around to trying this out, I have some minor observations, but the current design is perfectly fine (in general and for a release as well).

- The dB accuracy could be reduced to just one decimal place. That would already be an optimistic view on achievable accuracy with an actual acoustic measurement in non-laboratory setting. The linear values (amplitude), on the other hand, could be extended to three decimal places.
- In the Harmonics view, repeating the frequency value four times seems a little bit redundant.
- Since there is a cursor now and I prefer the keyboard, is it possible to bind the movement of the cursor to, say, left and right arrows?
- Another idea would be to not even place the displayed values in a tooltip, but in a (bottom) status line (as in some CAD programs), especially since the value only depends on the x-axis position, although I would have no clear idea how to align multiple values (Harmonics).

**Comment by be1** [comment]
Thanks for your comments @molke-productions. I will look how to implement them. Some of them would be easy, others need some investigation. I like the idea of keyboard arrows. In the mean time I'll tag v1.4.2.
