### ISSUE TITLE
jack connection error on debian 11

### ISSUE THREAD

**Issue by SamHawkens** [molke-productions/qloud#17]
When I try to "start recording" a message box pops up
"Connect JACK ports before capturing".
![grafik](https://user-images.githubusercontent.com/5927245/145726767-90bac875-6dbd-4d58-9122-7208ced3203a.png)

qjackctl shows connections OK (screenshot attached). No error in messages.
![grafik](https://user-images.githubusercontent.com/5927245/145726746-8943cc35-be80-4cf5-81ad-f7e9a76e64dd.png)

Test tone with jack_simple_client works OK. Am I missing something?

**Comment by molke-productions** [comment]
The [_Patchbay_](https://www.rncbc.org/drupal/node/76) connections seem fine if the configuration corresponds to you hardware. Can you find out what is actually connected when you get that message from the _Connections_ window?

**Comment by SamHawkens** [comment]
Thanks for pointing this out. I ran into the usual mistake and confused the patchbay with the actual connections. When draw in the connections window everything is fine.

**Comment by molke-productions** [comment]
With analog patchbays in mind, I see how the terminology could be misleading (although I can’t suggest a better one). I’m glad this already solved the issue.
