### ISSUE TITLE
step response plot broken?

### ISSUE THREAD

**Issue by SamHawkens** [molke-productions/qloud#18]
step response should be one single constant step when qloud out is connected to in via loopback. Plot looks completely wrong.

Steps to reproduce:

jack configuration
![grafik](https://user-images.githubusercontent.com/5927245/146167802-faf1f536-8c52-419a-b086-2b57a52288c3.png)

qloud configuration
![grafik](https://user-images.githubusercontent.com/5927245/146168619-d815d0f4-1238-4e96-82c7-3b12a509f260.png)

frequency response plot looks good
![grafik](https://user-images.githubusercontent.com/5927245/146168693-a0e52b02-5c26-45ec-85cd-1fe761e3e247.png)

impulse response looks good
![grafik](https://user-images.githubusercontent.com/5927245/146168845-f26dc360-85b7-4abc-b432-72aa83f437ce.png)

step response looks bad
![grafik](https://user-images.githubusercontent.com/5927245/146168931-d08ec290-e382-41a5-909c-2266e9424af3.png)

**Comment by molke-productions** [comment]
To be honest, I had not really needed the step response plot so far. I’m certainly no signal processing expert, but are you sure that the expected step response should be ideal with a bandpass-filtered input? [This one](http://www.matheonics.com/Filters/sample_bp.html) looks somehow similar to me, and with real-life input, the step response always seemed at least reasonable.

**Comment by SamHawkens** [comment]
I must admit my signal processing knowledge is somewhat basic. Of course we are regarding a bandpass windowed signal that will not result in an ideal step. Here are some step response examples for ideal and real world speakers. 
[https://www.fairaudio.de/lexikon/sprungantwort/](url)

Fig. 2 "sehr gute Sprungantwort" would be close.

**Comment by be1** [comment]
On the old qloud "qwt" version, the step response looks the same:
![Capture d’écran du 2021-12-16 05-55-53](https://user-images.githubusercontent.com/29155/146310890-3f739a8a-fe97-4965-9dec-81ef80fa3cad.png)
.

**Comment by SamHawkens** [comment]
Thanks for the feedback. Maybe it is an old issue. When I find some time I will have a look into the code.

**Comment by gaydenko** [comment]
I guess result is correct as long as we use limited frequency band. Try expand the band (and excitation duration) and investigate the difference.
