### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by trebmuh** [molke-productions/qloud#6]
It'd be great to be able to have the GUI translated.
I'd probably be able to provide a French translation of the GUI within a few weeks if the Qt translation mechanism was in place.

**Comment by be1** [comment]
I'll be able to generate a qloud_fr.qm today i think.

**Comment by be1** [comment]
French translation is now done. See 403d4518d593317cd79cf580899767d46c2afc94

**Comment by trebmuh** [comment]
@be1 : super !

**Comment by trebmuh** [comment]
@be1 : super !

See #11

**Comment by be1** [comment]
Je vais merger tes modifications, merci.
@trebmuh je viens d'ajouter des chaînes traductibles, mais je ne les ai pas traduites. si tu veux... a5195749d539878db355d1fda3cad34ad235e0cf

**Comment by be1** [comment]
@trebmuh c'est fait. J'avais le temps de le faire. 0f1aca5b24ff8f1318c152ef7d594b5290cc6dca

**Comment by trebmuh** [comment]
@be1: chouette. J'ai fait une passe dessus : #13
