### ISSUE TITLE
Connect JACK ports before capturing!

### ISSUE THREAD

**Issue by HuongNV96** [molke-productions/qloud#8]
Hi all

When start recording I have got error mess as "Connect JACK ports before capturing!"

Can you help me ?

**Comment by gaydenko** [comment]
Look at https://github.com/rncbc/qjackctl
Then use it to do literally that error message says :)

**Comment by HuongNV96** [comment]
> Look at https://github.com/rncbc/qjackctl
> Then use it to do literally that error message says :)

Than you,

**Comment by HuongNV96** [comment]
@gaydenko   did share link to fix ...!
