### ISSUE TITLE
Config jackaudio

### ISSUE THREAD

**Issue by HuongNV96** [molke-productions/qloud#9]
Hi all,

My pc using mic usb and 3.5 port to measurement. But recorded file not like with played file . I using gui to config jack audio as attached picture .
 
Can you help me ?
[test.zip](https://github.com/molke-productions/qloud/files/5286184/test.zip)

**Comment by gaydenko** [comment]
Excitation and filter wav files are Ok. But itTrimmed look is not expected. I have attached an image, and on the left size you can see expected look of IR, while on the right side is your IR Trimmed.
How does your qjackctl connection graph looks?
![IRs-left-expected-rigfht-strange](https://user-images.githubusercontent.com/3740016/94335075-8e661280-ffe1-11ea-9367-7b1f7ac83943.png)

**Comment by HuongNV96** [comment]
> Excitation and filter wav files are Ok. But irTrimmed look is not expected. I have attached an image, and on the left size you can see expected look of IR, while on the right side is your IR Trimmed.
> How does your qjackctl connection graph look?
> ![IRs-left-expected-rigfht-strange](https://user-images.githubusercontent.com/3740016/94335075-8e661280-ffe1-11ea-9367-7b1f7ac83943.png)

_UI,_
![image](https://user-images.githubusercontent.com/45852330/94382889-91d7d600-0168-11eb-8532-c8a64cf8ae12.png)
_Setting_ , I do default config, change input devices
![image](https://user-images.githubusercontent.com/45852330/94382927-b8960c80-0168-11eb-98b4-a02a32760281.png)
_Connection_ 
![image](https://user-images.githubusercontent.com/45852330/94382961-da8f8f00-0168-11eb-9694-f1459820a400.png)

Can you help me to review them ?
@gaydenko

**Comment by HuongNV96** [comment]
This new ir :
![image](https://user-images.githubusercontent.com/45852330/94384781-981c8100-016d-11eb-8549-46d1f0c52be4.png)
Simply , It looks more correct, doesn't it ?
@gaydenko

**Comment by gaydenko** [comment]
> [22.zip](https://github.com/molke-productions/qloud/files/5289666/22.zip)
> This new ir :
> ![image](https://user-images.githubusercontent.com/45852330/94384781-981c8100-016d-11eb-8549-46d1f0c52be4.png)
> Simply , It looks more correct, doesn't it ?
> @gaydenko

Yes, it does.

BTW, on connection graph the are double-connections. Why? The chain is:

- qloud out
- single-channel playback in
- loudspeaker
- mic
- mic amp
- sound card capture single-channel input

That is everything must be mono rather stereo. You are testing a single speaker (or what) at a time.
